# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hole
subtitle: ''
description: ''
keywords: Linux Network I/O
author: zyj
email: yujiuzhao@gmail.com
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ayer
theme_config:
  # 侧边栏菜单
  menu:
    主页: /
    归档: /archives
    分类: /categories
    标签: /tags
    关于我: /about
  
  # 站点次标题和打字动效
  # https://github.com/mattboldt/typed.js
  subtitle:
    enable: false # 是否开启动效
    text: TIME IS CHANGE # 滚动播放，如果不需要可以留空
    text2:
    text3:
  
  # 打赏
  # 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
  reward_type: 2
  # 打赏wording
  reward_wording: "请我喝杯咖啡吧~"
  # 支付宝二维码图片地址，跟你设置logo的方式一样。比如：/images/alipay.jpg
  alipay: /tks/alipay.jpg
  # 微信二维码图片地址
  weixin: /tks/wechat.jpg
  
  # 1、Valine[一款快速、简洁且高效的无后端评论系统](https://github.com/xCss/Valine)
  # 启用Valine必须先创建leancloud应用， 获取 id|key 填入即可
  leancloud:
    enable: true
    app_id: bvuA6HBJozJGUOpgxsFh2bIL-MdYXbMMI
    app_key: SXQ7K3p1k6CqkUVxXLUHA8H5
  # Valine配置
  valine:
    enable: true # 是否启用
    avatar: monsterid # 头像样式(https://valine.js.org/avatar.html)
    placeholder: 给我的文章加点评论吧~ # placeholder
  


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:mixWind/mixWind.github.io.git
  branch: master
